server:
  port: 8180
  servlet:
    context-path: /backend

security:
  ignored:
    - "*.bundle.*"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password